apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mydeploy
  labels:
    app: app-mydeploy
spec:
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:   
      containers:   
        - name: appdeploy   
          image: niranjanv64/microsvc-static-1:v1 
          ports: 
            - containerPort: 7050   
          args: ["com.microsvc.static1.Static1Application"]
          envFrom:
          - configMapRef:
              name: map-mydeploy
